In [1]:
import requests as req 
import pandas as pd
import json
import matplotlib.pyplot as plt
from datetime import datetime
import seaborn as sns
url = "https://github.com/ethen8181/machine-learning/blob/master/python/cohort/relay-foods.csv"
df = pd.read_csv(url + "?raw=true")
df=df[['OrderDate','UserId','TotalCharges']]
df['OrderDate']=pd.to_datetime(df['OrderDate'])
df['TotalCharges']=(df['TotalCharges'].apply(lambda x:x.replace('$',''))).astype(float)
get_year_month=lambda x:datetime(x.year,x.month,1)
df['OrderMonth']=df['OrderDate'].apply(get_year_month)

df['CohortMonth']=df.groupby('UserId')['OrderDate'].transform(min)
df['CohortMonth']=df['CohortMonth'].apply(lambda x:datetime(x.year,x.month,1))
years_diff=df['OrderMonth'].dt.year-df['CohortMonth'].dt.year
month_diff=df['OrderMonth'].dt.month-df['CohortMonth'].dt.month
df['cohortIndex']=years_diff*12+month_diff*1
grouping_count=df.groupby(['CohortMonth','cohortIndex'])
cohort_data = df.groupby(['CohortMonth','cohortIndex'])['UserId'].apply(pd.Series.nunique)
cohort_data = cohort_data.reset_index()
cohort_user_counts = cohort_data.pivot(index='CohortMonth',
                                  columns='cohortIndex',
                                  values='UserId')

cohort_sizes = cohort_user_counts.iloc[:,0]
retention = cohort_user_counts.divide(cohort_sizes, axis=0)
retention

cohortIndex,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
CohortMonth,,,,,,,,,,,,,,,
2009-01-01,1.0,0.363636,0.454545,0.409091,0.454545,0.363636,0.363636,0.318182,0.318182,0.318182,0.318182,0.363636,0.500000,0.318182,0.272727
2009-02-01,1.0,0.200000,0.333333,0.066667,0.266667,0.266667,0.266667,0.333333,0.333333,0.266667,0.200000,0.200000,0.333333,NaN,NaN
2009-03-01,1.0,0.307692,0.384615,0.307692,0.076923,0.153846,0.153846,0.230769,0.153846,0.076923,0.230769,0.153846,0.076923,NaN,NaN
2009-04-01,1.0,0.333333,0.256410,0.333333,0.153846,0.179487,0.102564,0.153846,0.051282,0.102564,0.076923,0.051282,NaN,NaN,NaN
2009-05-01,1.0,0.260000,0.240000,0.100000,0.080000,0.120000,0.060000,0.100000,0.100000,0.080000,0.060000,NaN,NaN,NaN,NaN
2009-06-01,1.0,0.468750,0.281250,0.187500,0.218750,0.156250,0.093750,0.093750,0.312500,0.093750,NaN,NaN,NaN,NaN,NaN
2009-07-01,1.0,0.460000,0.260000,0.200000,0.220000,0.200000,0.220000,0.140000,0.140000,NaN,NaN,NaN,NaN,NaN,NaN
2009-08-01,1.0,0.354839,0.290323,0.225806,0.193548,0.258065,0.129032,0.129032,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-09-01,1.0,0.405405,0.378378,0.216216,0.351351,0.243243,0.216216,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-10-01,1.0,0.314815,0.222222,0.240741,0.240741,0.129630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-11-01,1.0,0.246154,0.200000,0.223077,0.100000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-12-01,1.0,0.261538,0.276923,0.107692,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-01-01,1.0,0.526316,0.273684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-02-01,1.0,0.190000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-03-01,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN